import './globals.css';
import '@blocknote/core/fonts/inter.css';
import '@blocknote/mantine/style.css';
import '@liveblocks/react-ui/styles.css';
import '@liveblocks/react-ui/styles/dark/media-query.css';
import '@liveblocks/react-tiptap/styles.css';
import type { Metadata } from 'next';
import Providers from './providers';
import { Toaster } from '@/components/ui/sonner';
import { auth } from '@/lib/auth';
export const metadata: Metadata = {
  title: 'SyncSpace',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers session={session}>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
