import './globals.css';
import '@blocknote/core/fonts/inter.css';
import '@blocknote/mantine/style.css';
import '@liveblocks/react-ui/styles.css';
import '@liveblocks/react-ui/styles/dark/media-query.css';
import '@liveblocks/react-tiptap/styles.css';
import type { Metadata } from 'next';
import Providers from './Providers/queryProviders';
import { Toaster } from '@/components/ui/sonner';
import { auth } from '@/lib/auth';
import TanstackProvider from './Providers/tanstackProvider';
export const metadata: Metadata = {
  title: 'SyncSpace',
  description: 'Generated by create next app',
};
//[#fafaf5]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();
  return (
    <html lang="en">
      <body className={`antialiased bg-white`}>
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
