import './globals.css';
import '@blocknote/core/fonts/inter.css';
import '@blocknote/mantine/style.css';
import '@liveblocks/react-ui/styles.css';
import '@liveblocks/react-ui/styles/dark/media-query.css';
import '@liveblocks/react-tiptap/styles.css';

import type { Metadata } from 'next';
import Script from 'next/script';
import { Toaster } from '@/components/ui/sonner';
import TanstackProvider from './Providers/tanstackProvider';
import { GoogleTagManager } from '@next/third-parties/google';
export const metadata: Metadata = {
  title: 'TeamSpace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-PFVTZGHP" />
      <body className="antialiased bg-white">
        <Script id="microsoft-clarity" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "wkuk0cgpy5");
          `}
        </Script>

        <TanstackProvider>{children}</TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
